CONTACT:
  email: linder@embl.de
  person: Bastian Linder
INPUT:
    exp_mat: samples.tsv
LOCAL:
    temp-directory: /tmpdata/linder
    memory: 4g
    fastq: /scratch/linder/fastq/B122
    results: results
    logs: logs
    common_conda: envs/preprocess.yaml
META:
    species:
        homo_sapiens:
            build: GRCh37
            release: v29
    reference-directory: /scratch/linder/genomes
    #genome_download_path: "ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_29/GRCh38.primary_assembly.genome.fa.gz"
    #annotation_download_path: "ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_29/gencode.v29.annotation.gtf.gz"
    genome_download_path: "ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_29/GRCh37_mapping/GRCh37.primary_assembly.genome.fa.gz"
    annotation_download_path: "ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_29/GRCh37_mapping/gencode.v29lift37.annotation.gtf.gz"
    
    gtf_biotypes: gtf_biotypes.yaml
FILTER:
    FLEXBAR:
        adapter_R1: adapters/NEBnext_smallRNA_read1.fasta
